FROM pytorch/pytorch:1.13.0-cuda11.6-cudnn8-runtime

# Copy Tangram specific requirements to container
COPY requirements/minimal-requirements.txt /requirements.txt

# Install Tangram and its dependenciess
RUN pip install numpy
RUN pip install -r /requirements.txt