FROM pytorch/pytorch:1.12.1-cuda11.3-cudnn8-runtime

# Copy Tangram specific requirements to container
COPY requirements/minimal-requirements.txt /requirements.txt

# Install Tangram and its dependenciess
RUN pip install numpy
RUN pip install -r /requirements.txt