FROM ubuntu:22.04

ENV DEBIAN_FRONTEND noninteractive

# Installing Python
RUN apt update
RUN apt install -y software-properties-common dirmngr libffi-dev
RUN apt update
RUN apt install -y python3 wget git make python3-pip
RUN apt update

# Installing R 
RUN wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc
RUN add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/'
RUN apt install --no-install-recommends -y r-base

# Copy CellphoneDB specific requirements
COPY requirements/cpdb-requirements.txt /requirements.txt

# Install CellphoneDB and its dependencies
RUN pip install -r requirements.txt

# Check to make sure that CellphoneDB works
RUN cellphonedb database list_remote