name: scrna-test
channels:
  - intel
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - anyio
  - appnope
  - argon2-cffi
  - argon2-cffi-bindings
  - asttokens
  - attrs
  - babel
  - backcall
  - beautifulsoup4
  - blas
  - bleach
  - brotlipy
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - cryptography
  - debugpy
  - decorator
  - defusedxml
  - entrypoints
  - executing
  - gettext
  - giflib
  - glib
  - gst-plugins-base
  - gstreamer
  - icu
  - idna
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jedi
  - jpeg
  - json5
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyter_server
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - krb5
  - lerc
  - libclang
  - libcxx
  - libdeflate
  - libedit
  - libffi
  - libiconv
  - libllvm12
  - libpng
  - libpq
  - libsodium
  - libtiff
  - libwebp
  - libwebp-base
  - libxml2
  - libxslt
  - llvm-openmp
  - lz4-c
  - markupsafe
  - matplotlib-inline
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - nbclassic
  - nbclient
  - nbconvert
  - nbformat
  - ncurses
  - nest-asyncio
  - notebook
  - nspr
  - nss
  - numpy-base
  - openssl
  - packaging
  - pandocfilters
  - parso
  - pcre
  - pexpect
  - pickleshare
  - pip
  - ply
  - prometheus_client
  - prompt-toolkit
  - prompt_toolkit
  - psutil
  - ptyprocess
  - pure_eval
  - pycparser
  - pygments
  - pyopenssl
  - pyparsing
  - pyqt
  - pyrsistent
  - pysocks
  - python==3.8.15
  - python-dateutil
  - python-fastjsonschema
  - pyzmq
  - qt-main
  - qt-webengine
  - qtconsole
  - qtpy
  - qtwebkit
  - readline
  - requests
  - send2trash
  - sip
  - six
  - sniffio
  - soupsieve
  - sqlite
  - stack_data
  - tbb
  - terminado
  - testpath
  - tk
  - toml
  - tornado
  - traitlets
  - typing-extensions
  - typing_extensions
  - urllib3
  - wcwidth
  - webencodings
  - websocket-client
  - wheel
  - widgetsnbextension
  - xz
  - zeromq
  - zlib
  - zstd
  - pip:
    - anndata
    - anndata2ri
    - contourpy
    - cycler
    - dunamai
    - fonttools
    - get-version
    - gitdb
    - gitpython
    - h5py
    - jinja2
    - joblib
    - kiwisolver
    - llvmlite
    - matplotlib
    - natsort
    - networkx
    - numba
    - numexpr
    - numpy
    - pandas
    - patsy
    - pillow
    - pyan3
    - pyarrow
    - pynndescent
    - pyqt5-sip
    - pytz
    - pytz-deprecation-shim
    - rpy2
    - scanpy
    - scikit-learn
    - scipy
    - seaborn
    - setuptools
    - sinfo
    - smmap
    - statsmodels
    - stdlib-list
    - tables
    - threadpoolctl
    - tqdm
    - tzdata
    - tzlocal
    - umap-learn
